"""
BT3068 — /api/report Endpoint
================================
Generates PDF clinical decision support reports.
"""

import os
import io
import time
import base64
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional, List, Dict, Any

router = APIRouter()

class ReportRequest(BaseModel):
    prediction_result: Dict[str, Any]
    patient_id: Optional[str] = None
    notes: Optional[str] = None

@router.post("/report")
async def generate_report(request: ReportRequest):
    """
    Generate a PDF clinical decision support report.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise HTTPException(status_code=500, detail="fpdf2 not installed. Run: pip install fpdf2")
    
    pred = request.prediction_result
    patient_id = request.patient_id or f"ANON-{int(time.time())}"
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Header
    pdf.set_font('Helvetica', 'B', 20)
    pdf.cell(0, 15, 'ANTIGRAVITY NEURAL DIAGNOSTICS', ln=True, align='C')
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 8, 'BT3068 - Multi-Disease Detection Report', ln=True, align='C')
    pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(8)
    
    # Patient & Report Info
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'REPORT INFORMATION', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, f'Patient ID: {patient_id}', ln=True)
    pdf.cell(0, 6, f'Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', ln=True)
    pdf.cell(0, 6, f'Model: {pred.get("model_used", "EfficientNetB4+SE")}', ln=True)
    pdf.cell(0, 6, f'Domain: {pred.get("domain", "N/A").upper()}', ln=True)
    pdf.cell(0, 6, f'Inference Time: {pred.get("inference_time_ms", 0):.1f} ms', ln=True)
    pdf.ln(5)
    
    # Overall Diagnosis
    pdf.set_font('Helvetica', 'B', 14)
    diagnosis = pred.get("overall_diagnosis", "N/A")
    confidence = pred.get("confidence", 0)
    pdf.cell(0, 10, f'DIAGNOSIS: {diagnosis}', ln=True)
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 8, f'Confidence: {confidence * 100:.1f}%', ln=True)
    pdf.ln(5)
    
    # Predictions Table
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'CLASSIFICATION RESULTS', ln=True)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(70, 7, 'Disease', border=1)
    pdf.cell(40, 7, 'Probability', border=1)
    pdf.cell(40, 7, 'Risk Level', border=1)
    pdf.ln()
    
    pdf.set_font('Helvetica', '', 9)
    for p in pred.get("predictions", []):
        disease = p.get("disease", p) if isinstance(p, dict) else str(p)
        prob = p.get("probability", 0) if isinstance(p, dict) else 0
        risk = p.get("risk_level", "N/A") if isinstance(p, dict) else "N/A"
        pdf.cell(70, 7, str(disease), border=1)
        pdf.cell(40, 7, f'{prob * 100:.2f}%', border=1)
        pdf.cell(40, 7, str(risk), border=1)
        pdf.ln()
    
    pdf.ln(5)
    
    # Notes
    if request.notes:
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 8, 'CLINICAL NOTES', ln=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.multi_cell(0, 6, request.notes)
        pdf.ln(5)
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.multi_cell(0, 5,
        'DISCLAIMER: This report is generated by an AI-assisted diagnostic system '
        '(BT3068 - Multi-Disease Detection) and is intended for clinical decision support only. '
        'It does not constitute a medical diagnosis. All findings must be reviewed and confirmed '
        'by a qualified medical professional. IILM University, Greater Noida.')
    
    # Footer
    pdf.set_font('Helvetica', '', 7)
    pdf.cell(0, 10, f'Generated by ANTIGRAVITY v1.0.0 | {datetime.now().isoformat()}',
             ln=True, align='C')
    
    # Output PDF
    pdf_bytes = pdf.output()
    buffer = io.BytesIO(pdf_bytes)
    buffer.seek(0)
    
    filename = f"BT3068_Report_{patient_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
